# Generated by Django 5.0.7 on 2024-09-01 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="comment",
            field=models.TextField(
                blank=True, max_length=450, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=256, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(default=None, max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(default=None, max_length=50, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="client",
            name="surname",
            field=models.CharField(max_length=50, verbose_name="Отчество"),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("email", "owner")},
        ),
    ]
