# Generated by Django 5.0.7 on 2024-09-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "client",
            "0002_client_owner_alter_client_comment_alter_client_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Фамилия"),
        ),
    ]
