# Generated by Django 5.0.7 on 2024-09-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="owner",
        ),
    ]
