# Generated by Django 5.0.7 on 2024-09-01 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("data_mailing", models.DateTimeField(verbose_name="Начало")),
                (
                    "data_mailing_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершение"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("once_day", "раз в день"),
                            ("once_week", "раз в неделю"),
                            ("once_month", "раз в месяц"),
                        ],
                        max_length=10,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "создана"),
                            ("launched", "запущена"),
                            ("completed", "завершена"),
                        ],
                        max_length=9,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "client_mailing",
                    models.ManyToManyField(
                        to="client.client", verbose_name="Получатель"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
