# Generated by Django 5.0.7 on 2024-09-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
        ("message", "0002_remove_message_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="message.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
