# Generated by Django 5.0.7 on 2024-09-01 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_remove_mailing_user_mailing_message_mailing_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="data_mailing_finish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 1, 13, 20, 20, 165282, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата завершения",
            ),
        ),
    ]
