# Generated by Django 5.0.7 on 2024-09-03 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_data_mailing_finish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="data_mailing_finish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 3, 4, 25, 56, 849904, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата завершения",
            ),
        ),
    ]
